baseurl = "http://afrotechfest.co.uk"
languageCode = "en"
title = "AfroTech Fest"
theme = "hugo-universal-theme"
defaultContentLanguage = "en"

[menu]

# Main menu

[[menu.main]]
    name = "ABOUT THE FESTIVAL"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "WHO IS IT FOR"
    url  = "/#who-its-for"
    weight = 1

[[menu.main]]
    name = "TEAM"
    url  = "/#team"
    weight = 1

[[menu.main]]
    name = "SUBMIT PROPOSALS"
    url  = "/#proposals"
    weight = 1

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "AFROTECH FEST"
    subtitle = "A two-day festival by and for black people of African and Caribbean heritage."
    link_url = "#"
    link_text = "Read more"
