baseurl = "https://afrotechfest.co.uk/"
languageCode = "en"
title = "Afrotech Fest"
defaultContentLanguage = "en"


[menu]

# Main menu


[[menu.main]]
    name = "About the Festival"
    url  = "/#about"
    weight = 1

[[menu.main]]
    name = "Who is it for"
    url  = "/#who"
    weight = 2

[[menu.main]]
    name = "Submit a proposal"
    url  = "/#submit"
    weight = 3

[[menu.main]]
    name = "Team"
    url  = "/#team"
    weight = 4

    [[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 5

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    email = "test@example.com"
    latitude = 51.5243842
    longitude = -0.0730965
    copyright = "&copy; 2017 Afrotech Fest. Made with &#10084; in London"
    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyBh9951Ix-8r1OwdKOnapP0gUfeslNXe7E"
    defaultKeywords = ["tech", "tech fest", "afrotech fest", "diversity in tech", "black techies"]



[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"


[params.sponsors]
    enable = true
    title = "Our Sponsors"
    subtitle = ""


[params.team]
    enable = true
    title = "Our team"
    subtitle = ""
